john = 3
mary = 5
adam = 6
total_apples = john+mary+adam
print(  '\n\n\nEra uma vez... na Terra da Maçãs...',
        '\n\n   John tinha',john,'maçãs,',
        'Mary tinha',mary,'maçãs, e',
        'Adam tinha',adam,'maças.',
        '\nTodos eles foram muito felizes e viveram durante muito tempo.',
        '\nFim da história.',
        '\n\n Curiosidade!',
        '\n O total de maçãs usadas nessa estória foram',total_apples,'.'
        )